### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by GauteHaugen** [ChristofferHolmesland/InteraktivUndervisning#21]
#3 Continued
#9 Continued

### Todo:
- [x] Make a path in router.js for the user profile page
- [x] Make socket io function to comunicate on created to fill in information about the user
- [x] Make button, socket io function and logic to delete user data on request
- [x] Write bootstrap and css
