### ISSUE TITLE
Login functionality

### ISSUE THREAD

**Issue by ChristofferHolmesland** [ChristofferHolmesland/InteraktivUndervisning#3]
#9 Continued

Local user
Google / Facebook / Github login
Early sketch:
![login](https://user-images.githubusercontent.com/1873309/50830662-b6629d80-1348-11e9-9bc3-f99ab657d0e3.jpg)

### Done:
- [x] Make the view for the login page
- [x] Make socket io functions that is needed for a user to login
- [x] Setup passport to work with feide oauth and openid
- [x] Write a class to handle information about a user that is logged in
- [x] Find a way to handle users that are logged in
- [x] Write a script that will return a random name for people that sign in anonymously
- [x] Handle creating and very sessionId to the user in a timing attack safe way
- [x] Write the text needed for the page in the locale files

### Todo:
- [ ] Handle users that just close the browser and don't sign out
- [ ] Handle users that have been autheticated with feide and how to reautheticate them without them havving to log in again.

### Bug:
- [x] Socket.io function inside NavBar.vue inside the mounted(){} does not trigger on an emit from the server. The emit functions inside NavBa.vue does trigger the socket.io functions on the server
